version: "3.8"

services:
  traefik:
    image: traefik:v2.10
    command:
      - --configFile=/etc/traefik/traefik.prod.yml
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/traefik.prod.yml:/etc/traefik/traefik.prod.yml:ro
      - ./traefik/letsencrypt:/letsencrypt
    networks:
      - web

  frontend:
    build:
      context: ./frontend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.tls=true"
      - "traefik.http.routers.frontend.tls.certresolver=letsencrypt"
    expose:
      - "8000"
    networks:
      - web
    volumes:
      - ./frontend/static:/app/static
networks:
  web:
    external: false
